### ISSUE TITLE
neue Plugins werden nicht kopiert

### ISSUE THREAD

**Issue by Marx1st** [buwzim/moodle-update-script#7]
Hier das mahara-repository ist noch nicht vorgesehen und wird nicht kopiert.

**Comment by sennewood** [comment]
Wie lautet der Pfad?

**Comment by Marx1st** [comment]
./mod/assign/submission/mahara

**Comment by sennewood** [comment]
Sollte hiermit erledigt sein: https://github.com/buwzim/moodle-update-script/commit/099a1f8539585565431bba62b712828c1866e37f
